language: python
python:
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential cmake git pkg-config
  - sudo apt-get install -y libjpeg8-dev libtiff4-dev libjasper-dev libpng12-dev
  - sudo apt-get install -y mplayer2  ubuntu-restricted-extras
  - sudo apt-get install -y libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
  - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install -y python-opencv libav-tools
  - pip install -r requirements.txt
  # Soooooo ugly
  - pip uninstall -y opencv-python
  - pip install opencv-python
# command to run tests
script:
  - nosetests --with-coverage --cover-package=pluto
after_success:
  - coveralls

